{% set name = "exactextract" %}
{% set version = "0.2.0.dev199" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/81/59/1ab9815dd69e122ba58da030e9e7716f1df3f159ca50cf4c53d7b0ebc552/exactextract-0.2.0.dev199.tar.gz
  # url: https://test.pypi.io/packages/source/{{ name[0] }}/{{ name }}/exactextract-{{ version }}.tar.gz
  sha256: 2976e3519da485f13c972e57b0be06902075f15ea957cdc44c04f8ae0bd2056d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: True  # [win or py==38]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ stdlib("c") }}
  host:
    - python
    - geos
    - libgdal
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - exactextract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/isciences/exactextract
  summary: Fast and accurate raster zonal statistics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbaston
    - akrherz
