{% set name = "exactextract" %}
{% set version = "0.2.0.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exactextract-{{ version }}.tar.gz
  sha256: 7fc895e1f49e12cc84dc157274595d92576e760a0968378706452e539be26d2d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: True  # [win or osx or py==38]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ stdlib("c") }}
  host:
    - python
    - geos
    - libgdal
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - exactextract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/isciences/exactextract
  summary: Fast and accurate raster zonal statistics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbaston
    - akrherz
